-- Seed Data: Initial content population for Mehdi's Portfolio
-- Date: 2026-04-12
-- Note: Embeddings are NULL placeholders — will be generated by the backend embedding service

-- ============================================================
-- 1. Profile (single row)
-- ============================================================
INSERT INTO profiles (full_name, headline, bio, email, linkedin_url, github_url) VALUES
(
    'Mehdi Abbas Nathani',
    'Agentic AI & Software Engineer',
    'Mehdi is a passionate software engineer with an MBA in Finance and 10+ years of professional experience. He made the transition from Senior Finance Executive to Agentic AI & Software Engineering after realizing his deep passion for building software. His unique background in finance gives him a distinct perspective on fintech products and business automation. He holds certifications in Next.js, OpenAI Agents SDK, and Prompt Engineering, and specializes in Flutter/Dart, Python, and AI-powered applications.',
    'mehdi@example.com',
    'https://linkedin.com/in/mehdinathani',
    'https://github.com/mehdinathani'
);

-- ============================================================
-- 2. Projects
-- ============================================================
INSERT INTO projects (id, title, description, short_description, tech_stack, project_url, github_url, featured, order_index, start_date, end_date) VALUES
('a0000000-0000-0000-0000-000000000001', 'BIDLY', 'A comprehensive bidding and auction management platform built with Flutter. BIDLY enables users to create, browse, and participate in real-time auctions with a smooth, native mobile experience. Features include live bidding, user authentication, item listings with images, and real-time notifications.', 'Real-time auction and bidding platform built with Flutter', ARRAY['Flutter', 'Dart', 'Firebase', 'Cloud Firestore', 'Firebase Auth'], NULL, 'https://github.com/mehdinathani/bidly', true, 1, '2025-01-01', '2025-06-15'),
('a0000000-0000-0000-0000-000000000002', 'Hospital Reception System', 'An automated hospital reception management system that streamlines patient check-in, appointment scheduling, and visitor tracking. Built with Python and FastAPI for the backend with a PostgreSQL database for reliable data management.', 'Hospital automation system for reception management', ARRAY['Python', 'FastAPI', 'PostgreSQL', 'SQLAlchemy'], NULL, 'https://github.com/mehdinathani/hospital-reception', true, 2, '2025-06-01', '2025-12-01'),
('a0000000-0000-0000-0000-000000000003', 'AI Portfolio Platform', 'This dynamic portfolio website with an AI-powered RAG chatbot. Built with Next.js App Router, FastAPI backend, Supabase PostgreSQL with pgvector, and Google Gemini 1.5 Flash for intelligent, grounded responses about Mehdi''s background.', 'AI-powered portfolio with RAG chatbot', ARRAY['Next.js', 'TypeScript', 'FastAPI', 'Python', 'Supabase', 'pgvector', 'Gemini API'], NULL, NULL, true, 0, '2026-03-01', NULL);

-- ============================================================
-- 3. Skills
-- ============================================================
INSERT INTO skills (name, category, proficiency, order_index) VALUES
-- Languages
('Python', 'Languages', 5, 1),
('Dart', 'Languages', 5, 2),
('TypeScript', 'Languages', 4, 3),
('JavaScript', 'Languages', 4, 4),
('SQL', 'Languages', 4, 5),
-- Frameworks
('Flutter', 'Frameworks', 5, 1),
('FastAPI', 'Frameworks', 4, 2),
('Next.js', 'Frameworks', 4, 3),
('React', 'Frameworks', 4, 4),
-- Databases
('PostgreSQL', 'Databases', 4, 1),
('Firebase/Firestore', 'Databases', 4, 2),
('Supabase', 'Databases', 4, 3),
-- Tools
('Git', 'Tools', 5, 1),
('Docker', 'Tools', 3, 2),
('VBA/Excel Macros', 'Tools', 5, 3),
-- AI/ML
('RAG Pipelines', 'AI/ML', 4, 1),
('Prompt Engineering', 'AI/ML', 5, 2),
('OpenAI Agents SDK', 'AI/ML', 3, 3);

-- ============================================================
-- 4. Project-Skills Links
-- ============================================================
-- BIDLY (project 1) uses Flutter, Dart, Firebase
INSERT INTO project_skills (project_id, skill_id)
SELECT 'a0000000-0000-0000-0000-000000000001', id FROM skills WHERE name IN ('Flutter', 'Dart', 'Firebase/Firestore');

-- Hospital Reception (project 2) uses Python, FastAPI, PostgreSQL
INSERT INTO project_skills (project_id, skill_id)
SELECT 'a0000000-0000-0000-0000-000000000002', id FROM skills WHERE name IN ('Python', 'FastAPI', 'PostgreSQL');

-- AI Portfolio (project 3) uses Next.js, TypeScript, FastAPI, Python, Supabase, Gemini
INSERT INTO project_skills (project_id, skill_id)
SELECT 'a0000000-0000-0000-0000-000000000003', id FROM skills WHERE name IN ('Next.js', 'TypeScript', 'FastAPI', 'Python', 'Supabase', 'RAG Pipelines');

-- ============================================================
-- 5. Experience
-- ============================================================
INSERT INTO experience (company, role, start_date, end_date, responsibilities, order_index) VALUES
('IVISIATE GATE', 'Software Engineer', '2025-01-01', NULL, 'Leading development of mobile applications and automation solutions. Building cross-platform apps with Flutter and backend services with Python/FastAPI.', 1),
('Finance Industry', 'Senior Finance Executive', '2014-01-01', '2024-12-31', 'Managed financial operations, budgeting, and reporting for 10+ years. Developed advanced Excel/VBA automation tools for financial analysis and reporting. Identified the opportunity to transition into software engineering.', 2);

-- ============================================================
-- 6. Certifications
-- ============================================================
INSERT INTO certifications (name, issuer, date_earned, order_index) VALUES
('Next.js Development', 'SMIT', '2025-01-15', 1),
('OpenAI Agents SDK', 'OpenAI', '2025-02-01', 2),
('Prompt Engineering', 'DeepLearning.AI', '2025-02-15', 3),
('MBA in Finance', 'Business School', '2014-06-01', 4);

-- ============================================================
-- 7. Testimonials
-- ============================================================
INSERT INTO testimonials (author_name, author_role, quote, date, order_index) VALUES
('Ahmed Khan', 'Senior Developer at IVISIATE GATE', 'Mehdi brings a unique combination of financial acumen and engineering skill. His ability to understand business requirements and translate them into elegant technical solutions is remarkable.', '2025-06-01', 1),
('Sarah Ali', 'Product Manager', 'Working with Mehdi has been a great experience. He delivers high-quality code on time and always thinks about the user experience first.', '2025-08-15', 2);

-- ============================================================
-- 8. Knowledge Base (RAG chunks)
-- Note: Embeddings set to zeros as placeholders — run embedding generation script to populate
-- ============================================================
INSERT INTO knowledge_base (content, source, source_id, embedding, metadata) VALUES
('Mehdi Abbas Nathani is a software engineer with an MBA in Finance and 10+ years of professional experience. He transitioned from a Senior Finance Executive role to software engineering in 2025 after completing certifications in Next.js, OpenAI Agents SDK, and Prompt Engineering.', 'career_narrative', NULL, array_fill(0, ARRAY[768])::vector(768), '{"tags": ["background", "transition"], "priority": "high"}'),
('Mehdi specializes in Flutter/Dart for mobile development, Python/FastAPI for backend services, and TypeScript/Next.js for web applications. His finance background gives him unique expertise in fintech and business automation solutions.', 'bio', NULL, array_fill(0, ARRAY[768])::vector(768), '{"tags": ["skills", "specialization"], "priority": "high"}'),
('BIDLY is a real-time auction and bidding platform built with Flutter, Firebase, and Cloud Firestore. It features live bidding, user authentication, and item listings with images.', 'project', 'a0000000-0000-0000-0000-000000000001', array_fill(0, ARRAY[768])::vector(768), '{"tags": ["bidly", "flutter", "mobile"]}}'),
('The Hospital Reception System is an automated patient check-in and appointment scheduling system built with Python, FastAPI, and PostgreSQL. It streamlines front-desk operations in healthcare facilities.', 'project', 'a0000000-0000-0000-0000-000000000002', array_fill(0, ARRAY[768])::vector(768), '{"tags": ["hospital", "fastapi", "backend"]}'),
('Mehdi holds certifications in Next.js (SMIT 2025), OpenAI Agents SDK (OpenAI 2025), Prompt Engineering (DeepLearning.AI 2025), and an MBA in Finance (2014).', 'certification', NULL, array_fill(0, ARRAY[768])::vector(768), '{"tags": ["certifications", "education"]}'),
('Mehdi is available for full-time positions, freelance projects, and collaboration opportunities. He can be contacted through the portfolio website contact form or the AI chatbot.', 'resume', NULL, array_fill(0, ARRAY[768])::vector(768), '{"tags": ["contact", "availability"], "priority": "high"}'),
('At IVISIATE GATE, Mehdi leads development of mobile applications and automation solutions, building cross-platform apps with Flutter and backend services with Python/FastAPI.', 'career_narrative', NULL, array_fill(0, ARRAY[768])::vector(768), '{"tags": ["current-role", "experience"]}');

-- ============================================================
-- Verification Queries
-- ============================================================
SELECT 'Profile' AS table_name, COUNT(*) AS row_count FROM profiles
UNION ALL
SELECT 'Projects', COUNT(*) FROM projects
UNION ALL
SELECT 'Skills', COUNT(*) FROM skills
UNION ALL
SELECT 'Project Skills', COUNT(*) FROM project_skills
UNION ALL
SELECT 'Experience', COUNT(*) FROM experience
UNION ALL
SELECT 'Certifications', COUNT(*) FROM certifications
UNION ALL
SELECT 'Testimonials', COUNT(*) FROM testimonials
UNION ALL
SELECT 'Knowledge Base', COUNT(*) FROM knowledge_base;
